// <auto-generated />
namespace MacierzEinsenhoweraDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class dane_testowe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dane_testowe));
        
        string IMigrationMetadata.Id
        {
            get { return "201510011748309_dane_testowe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
